### ISSUE TITLE
KeyError: '1.4.6.3'

### ISSUE THREAD

**Issue by Erdene-Ochir0417** [tyzoh/DrQA-SHINRA#1]
Hello, thanks for sharing code
I have problem with convert data to shinra 2018 format and this error occured. Could you share shinra dataset which is converted into squad format?

File "scripts/shinra/shinra2019_to_2018.py", line 64, in <module>
    main()
  File "scripts/shinra/shinra2019_to_2018.py", line 44, in main
    process(dataset_2019)
  File "scripts/shinra/shinra2019_to_2018.py", line 23, in process
    all_attributes[page_id]['Attributes_html'] = {att:[] for att in attr_list.attrs[ENE]}
KeyError: '1.4.6.3'

**Comment by ebal5** [comment]
Have you downloaded Shinra 2019(or maybe 2020) JP Tasks data?
I think you can download it from [here](http://shinra-project.info/download/#2019jp) (you need to have an account).

**Comment by aiishii** [comment]
Hi, Erdene-Ochir0417.
Sorry for the delay in replying to you.

As ebal5 commented, there is a requirement to download and place the data from SHINRA web site.
Thank you for your help, ebal5!

This is different from Erdene-Ochir0417's error, but when I ran the program with the current downloadable data of SHINRA web, I found that the following error occurred because some of the attribute values were named in the old version.

> Traceback (most recent call last):
>   File "scripts/shinra/shinra2019_to_2018.py", line 64, in <module>
>     main()
>   File "scripts/shinra/shinra2019_to_2018.py", line 44, in main
>     process(dataset_2019)
>   File "scripts/shinra/shinra2019_to_2018.py", line 29, in process
>     all_attributes[page_id]['Attributes_html'][attribute].append(html_offset)
> KeyError: '読み'

Therefore, I have modified the following file and I would like you to use it.

- scripts/shinra/attr_list.py
- scripts/shinra/convert.sh
- scripts/shinra/shinra_to_squad.py
